name: Deploy Personal Meme Survey to GitHub Pages

on:
  push:
    paths:
      - 'survey/personal_meme_survey/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: survey/personal_meme_survey

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build the React app
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: survey/personal_meme_survey/dist
          destination_dir: survey/personal_meme_survey
          publish_branch: gh-pages
          force_orphan: true